Dashboard/urls.py
from django.urls import path, include
from rest_framework import routers

from Dashboard import views
from Dashboard.api_views import PersonViewSet, DepartmentViewSet, CourseViewSet, StudentViewSet, LecturerViewSet, \
    TimetableViewSet
from Dashboard.views import HomeView, LoginView, ForgotPasswordView, ChangePasswordView, RegisterView, SettingsView, \
    CoursesView, LogoutView

app_name = "Dashboard"

router = routers.DefaultRouter()
router.register('department', DepartmentViewSet)
router.register('course', CourseViewSet)
router.register('person', PersonViewSet)
router.register('student', StudentViewSet)
router.register('lecturer', LecturerViewSet)
router.register('timetable', TimetableViewSet)

urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('register', RegisterView.as_view(), name="register"),
    path('forgot_password', ForgotPasswordView.as_view(), name="forgot_password"),
    path('forgot_password/change_password<int:user_id>', ChangePasswordView.as_view(), name="change_password"),
    path('account/dashboard', HomeView.as_view(), name="home"),
    path('account/generate', views.generate_timetable, name="generate"),
    path('account/settings', SettingsView.as_view(), name="settings"),
    path('account/settings/<str:username>', SettingsView.as_view(), name="settings"),
    path('account/courses', CoursesView.as_view(), name="courses"),
    path('account/courses/toggle<str:course_code>', views.toggle_course, name="toggle_course"),
    path('api', include(router.urls)),
]

Timetable/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Dashboard.urls'))
]

Dashboard/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=125, choices=[
                ('COMPUTER SCIENCES', 'COMPUTER SCIENCES'),
                ('BIOLOGICAL SCIENCES', 'BIOLOGICAL SCIENCES'),
                ('CHEMICAL SCIENCES', 'CHEMICAL SCIENCES'),
                ('MANAGEMENT SCIENCES', 'MANAGEMENT SCIENCES'),
                ('MASS COMMUNICATION', 'MASS COMMUNICATION'),
                ('CRIMINOLOGY', 'CRIMINOLOGY'),
                ('GENERAL STUDIES', 'GENERAL STUDIES'),
            ])

    def __str__(self):
        return self.name


class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    code = models.CharField(max_length=10)
    unit = models.PositiveIntegerField()

    def __str__(self):
        return self.title


class Person(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    last_name = models.CharField(max_length=250)
    first_name = models.CharField(max_length=250)

    def __str__(self):
        return self.user


class Student(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    matric_no = models.CharField(max_length=30)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)

    def __str__(self):
        return self.matric_no


class Lecturer(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    staff_id = models.CharField(max_length=30)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)

    def __str__(self):
        return self.staff_id


class Timetable(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    day = models.CharField(max_length=20)
    slot = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.course} - {self.day} - {self.slot}"

Dashboard/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from Dashboard.forms import LoginForm, ForgotPasswordForm, ChangePasswordForm, UpdatePasswordForm, RegisterForm
from Dashboard.function import change_course_to_dict, genetic_algorithm, convert_day_to_string, convert_slot_to_string, \
    convert_day_to_int, convert_slot_to_int
from Dashboard.models import Person, Lecturer, Student, Course, Department, Timetable


# Create a login view
class LoginView(View):
    # Add template name
    template_name = 'dashboard/login.html'

    # Create get function
    def get(self, request):
        # Check if user is logged in
        if request.user.is_authenticated and not request.user.is_superuser:
            # Redirect back to dashboard if true
            return HttpResponseRedirect(reverse('Dashboard:home'))
        # Otherwise
        else:
            #  Get login form
            form = LoginForm()
            # load the page with the form
            return render(request, self.template_name, {'form': form})

    # Create post function to process te form on submission
    def post(self, request):
        # Get the submitted form
        form = LoginForm(request.POST)
        #  Check if the form is valid
        if form.is_valid():
            # Process the input
            username = form.cleaned_data['username'].strip()
            password = form.cleaned_data['password'].strip()
            # Authenticate the user login details
            user = authenticate(request, username=username, password=password)
            # Check if user exists
            if user is not None:
                # Log in the user
                login(request, user)
                # Redirect to dashboard page
                return HttpResponseRedirect(reverse('Dashboard:home'))
            # If user does not exist
            else:
                # Create an error message
                messages.error(request, "Invalid login details")
                # Redirect back to the login page
                return HttpResponseRedirect(reverse('Dashboard:login'))


# Create a forgot password view
class ForgotPasswordView(View):
    # Add template name
    template_name = 'dashboard/forgot_password.html'

    # Create get function
    def get(self, request):
        # Check if user is logged in
        if request.user.is_authenticated and not request.user.is_superuser:
            # Redirect back to dashboard if true
            return HttpResponseRedirect(reverse('Dashboard:home'))
        # Otherwise
        else:
            form = ForgotPasswordForm()
            # load the page with the form
            return render(request, self.template_name, {'form': form})

    # Create post function to process the form on submission
    def post(self, request):
        # Get the submitted form
        form = ForgotPasswordForm(request.POST)
        #  Check if the form is valid
        if form.is_valid():
            user_id = form.cleaned_data['user_id'].strip()
            email = form.cleaned_data['email'].strip()

            if User.objects.filter(**{'username': user_id, 'email': email}).exists():
                user = User.objects.get(username=user_id)
                # Redirect back to dashboard if true
                return HttpResponseRedirect(reverse('Dashboard:change_password', args=(user.id,)))
            else:
                messages.success(request, "User details does not match")
                # Redirect back to page
                return HttpResponseRedirect(reverse('Dashboard:forgot_password'))


# Create an update password view
class ChangePasswordView(View):
    template_name = 'dashboard/change_password.html'

    def get(self, request, user_id):
        # Check if user is logged in
        if request.user.is_authenticated and not request.user.is_superuser:
            # Redirect back to dashboard if true
            return HttpResponseRedirect(reverse('Dashboard:home'))
        # Otherwise
        else:
            form = ChangePasswordForm()
            user = get_object_or_404(User, id=user_id)
            context = {'user': user, 'user_id': user_id, 'form': form}
            return render(request, self.template_name, context)

    def post(self, request, user_id):
        if request.method == 'POST':
            form = ChangePasswordForm(request.POST)
            if form.is_valid():
                password1 = form.cleaned_data['password'].strip()
                password2 = form.cleaned_data['confirm_password'].strip()

                if password1 == "password":
                    messages.error(request, "Password cannot be 'password'")
                    return HttpResponseRedirect(reverse('Dashboard:update_password', args=(user_id,)))

                else:
                    if password1 == password2:
                        user = User.objects.get(id=user_id)
                        user.set_password(password1)
                        user.save()

                        messages.success(request, 'Password successfully changed')
                        return HttpResponseRedirect(reverse('Dashboard:login'))
                    else:
                        messages.error(request, "Password does not match")
                        return HttpResponseRedirect(reverse('Dashboard:update_password', args=(user_id,)))


class RegisterView(View):
    template_name = "dashboard/register.html"

    def get(self, request):
        # Check if user is logged in
        if request.user.is_authenticated and not request.user.is_superuser:
            # Redirect back to dashboard if true
            return HttpResponseRedirect(reverse('Dashboard:home'))
        # Otherwise
        else:
            form = RegisterForm()
            # Go to the register page
            return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            last_name = form.cleaned_data['last_name'].strip().upper()
            first_name = form.cleaned_data['first_name'].strip().upper()
            user_id = form.cleaned_data['user_id'].strip().upper()
            email = form.cleaned_data['email'].strip()
            department = form.cleaned_data['department'].strip()
            post = form.cleaned_data['post']
            password = form.cleaned_data['password'].strip()
            confirm_password = form.cleaned_data['confirm_password'].strip()

            if User.objects.filter(**{"username": user_id, "email": email}).exists():
                messages.error(request, "User already exists")
                return HttpResponseRedirect(reverse("Dashboard:register"))
            else:
                if password == confirm_password:
                    user = User.objects.create_user(username=user_id, password=password, email=email)
                    person = Person.objects.create(user=user, last_name=last_name, first_name=first_name)
                    department = Department.objects.get(name=department)
                    if post == "LECTURER":
                        Lecturer.objects.create(person=person, staff_id=user_id, department=department)
                    else:
                        Student.objects.create(person=person, matric_no=user_id, department=department)
                    messages.success(request, "Registration successful")
                    return HttpResponseRedirect(reverse("Dashboard:login"))
                else:
                    messages.error(request, "Passwords does not match")
                    return HttpResponseRedirect(reverse("Dashboard:register"))


class HomeView(View):
    template_name = "dashboard/home.html"

    @method_decorator(login_required)
    def get(self, request):
        # Check if user is not logged in
        if request.user.is_superuser:
            # Redirect back to dashboard if true
            return HttpResponseRedirect(reverse('Dashboard:login'))
        # Otherwise
        else:
            person = Person.objects.get(user=request.user)
            date = datetime.datetime.now().date()

            if Student.objects.filter(person=person).exists():
                current_user = Student.objects.get(person=person)
            else:
                current_user = Lecturer.objects.get(person=person)

            first = ['', '', '', '', '']
            second = ['', '', '', '', '']
            third = ['', '', '', '', '']
            fourth = ['', '', '', '', '']
            fifth = ['', '', '', '', '']
            sixth = ['', '', '', '', '']
            seventh = ['', '', '', '', '']
            eighth = ['', '', '', '', '']
            for t in Timetable.objects.all():
                course = t.course

                if convert_slot_to_int(t.slot) == 0:
                    first[convert_day_to_int(t.day)] += f"{course.code}\n"
                elif convert_slot_to_int(t.slot) == 1:
                    second[convert_day_to_int(t.day)] += f"{course.code}\n"
                elif convert_slot_to_int(t.slot) == 2:
                    third[convert_day_to_int(t.day)] += f"{course.code}\n"
                elif convert_slot_to_int(t.slot) == 3:
                    fourth[convert_day_to_int(t.day)] += f"{course.code}\n"
                elif convert_slot_to_int(t.slot) == 4:
                    fifth[convert_day_to_int(t.day)] += f"{course.code}\n"
                elif convert_slot_to_int(t.slot) == 5:
                    sixth[convert_day_to_int(t.day)] += f"{course.code}\n"
                elif convert_slot_to_int(t.slot) == 6:

Dashboard/templates/dashboard/change_password.html
{% extends 'auth.html' %}

{% load static %}

{% block title %}Change Password{% endblock title %}

{% block content %}
<div class="col-sm-8 col-md-6 col-xl-9">
    <h2 class="mb-3 fs-7 fw-bolder">Timetable Management System</h2>
    <div class="position-relative text-center my-4">
        <p class="mb-0 fs-4 px-3 d-inline-block bg-white text-dark z-index-5 position-relative">Change Password</p>
        <span class="border-top w-100 position-absolute top-50 start-50 translate-middle"></span>
    </div>
    <div id="toast">
        {% for message in messages %}
        <div class="alert alert-info" role="alert"><strong>Message: </strong><i>{{ message }}</i></div>
        {% endfor %}
    </div>
    <form method="post" action="">
        {% csrf_token %}
        {% include 'dashboard/form.html' with form=form %}
        <button type="submit" class="btn btn-primary w-100 py-8 mb-4 rounded-2">Submit</button>
    </form>
</div>
{% endblock content %}

{% block ajax %}
$("#toast").fadeIn(3000);
$("#toast").fadeOut(3000);
{% endblock ajax %}

Dashboard/templates/dashboard/courses.html
{% extends 'base.html' %}

{% load static %}

{% block title %}My Courses{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="card bg-light-info shadow-none position-relative overflow-hidden">
        <div class="card-body px-4 py-3">
            <div class="row align-items-center">
                <div class="col-9">
                    <h4 class="fw-semibold mb-8">My Courses</h4>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a class="text-muted" href="index.html">Home</a></li>
                            <li class="breadcrumb-item" aria-current="page">My Courses</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-3">
                    <div class="text-center mb-n5">
                        <img src="{% static 'dashboard/dist/images/breadcrumb/ChatBc.png' %}" alt=""
                             class="img-fluid mb-n4">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-account" role="tabpanel"
                     aria-labelledby="pills-account-tab" tabindex="0">
                    <div class="row">
                        <div class="col-lg-6 d-flex align-items-stretch">
                            <div class="card-body">
                                <div class="mb-3">
                                    <h4 class="card-title mb-0">Courses</h4>
                                </div>
                                <ul class="list-group">
                                    {% for course in user_courses %}
                                    <li class="list-group-item d-flex align-items-center">
                                        <i class="ti ti-box fs-4 me-2 text-primary"></i>
                                        {{ course.title }}
                                        <span class="badge bg-light-primary text-primary font-medium rounded-pill ms-auto">{{ course.code }}</span>
                                    </li>
                                    {% empty %}
                                    <li class="list-group-item d-flex align-items-center">
                                        <i class="ti ti-box fs-4 me-2 text-primary"></i>
                                        No Course has been registered by you.
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-6 d-flex align-items-stretch">
                            <div class="card-body">
                                <div class="mb-3">
                                    <h4 class="card-title mb-0">Statistics</h4>
                                </div>
                                <ul class="list-group">
                                    <li class="list-group-item d-flex align-items-center">
                                        <i class="ti ti-box fs-4 me-2 text-primary"></i>
                                        Number of Courses
                                        <span class="badge bg-light-primary text-primary font-medium rounded-pill ms-auto">{{ no_of_courses|default:0 }}</span>
                                    </li>
                                    <li class="list-group-item d-flex align-items-center">
                                        <i class="ti ti-box fs-4 me-2 text-primary"></i>
                                        Total Lecture Hours (Weekly)
                                        <span class="badge bg-light-primary text-primary font-medium rounded-pill ms-auto">{{ lecture_hrs|default:0 }}</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card card-body">
        <div class="table-responsive">
            <table class="table search-table align-middle text-nowrap">
                <thead class="header-item">
                <tr>
                    <th>Course Code</th>
                    <th>Course Title</th>
                    <th>Course Unit</th>
                    <th>Add/Remove</th>
                </tr>
                </thead>
                <tbody>
                {% for course in courses %}
                <!-- start row -->
                <tr class="search-items">
                    <td>
                        <h6 class="user-name mb-0">{{ course.title }}</h6>
                    </td>
                    <td>
                        <span class="usr-email-addr">{{ course.code }}</span>
                    </td>
                    <td>
                        <span class="usr-email-addr">{{ course.unit }}</span>
                    </td>
                    <td>
                        <div class="action-btn">
                            {% if course in user_courses %}
                            <a href="{% url 'Dashboard:toggle_course' course.code %}" class="btn btn-sm btn-danger w-100">Remove</a>
                            {% else %}
                            <a href="{% url 'Dashboard:toggle_course' course.code %}" class="btn btn-sm btn-primary w-100">Add</a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
                <!-- end row -->
                {% empty %}
                <!-- start row -->
                <tr class="search-items">
                    <td colspan="4">
                        <h6 class="user-name mb-0">No course available</h6>
                    </td>
                </tr>
                <!-- end row -->
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

Dashboard/templates/dashboard/forgot_password.html
{% extends 'auth.html' %}

{% load static %}

{% block title %}Forgot Password{% endblock title %}

{% block content %}
<div class="col-sm-8 col-md-6 col-xl-9">
    <h2 class="mb-3 fs-7 fw-bolder">Timetable Management System</h2>
    <div class="position-relative text-center my-4">
        <p class="mb-0 fs-4 px-3 d-inline-block bg-white text-dark z-index-5 position-relative">Recover Account</p>
        <span class="border-top w-100 position-absolute top-50 start-50 translate-middle"></span>
    </div>
    <div id="toast">
        {% for message in messages %}
        <div class="alert alert-info" role="alert"><strong>Message: </strong><i>{{ message }}</i></div>
        {% endfor %}
    </div>
    <form method="post" action="">
        {% csrf_token %}
        {% include 'dashboard/form.html' with form=form %}
        <button type="submit" class="btn btn-primary w-100 py-8 mb-4 rounded-2">Submit</button>
    </form>
</div>
{% endblock content %}

{% block ajax %}
$("#toast").fadeIn(3000);
$("#toast").fadeOut(3000);
{% endblock ajax %}

Dashboard/templates/dashboard/form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
</div>
{% endif %}

{% for field in form.visible_fields %}
<div class="mb-3">
    <label class="form-label">{{ field.label_tag }} </label>
    {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}

        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}

        {% else %}
        {% render_field field class="form-control" %}
         {% endif %}
    {% else %}
    {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
    <div class="help-block form-text with-errors form-control-feedback">{{ field.help_text }}</div>
    {% endif %}
</div>
{% endfor %}

Dashboard/templates/dashboard/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Dashboard{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="card bg-light-info shadow-none position-relative overflow-hidden">
        <div class="card-body px-4 py-3">
            <div class="row align-items-center">
                <div class="col-9">
                    <div class="d-flex align-items-center gap-4 mb-4">
                <div class="position-relative">
                    <div class="border border-2 border-primary rounded-circle">
                        <img src="{% static 'dashboard/dist/images/profile/user-1.jpg' %}" class="rounded-circle m-1"
                             alt="user1" width="60"/>
                    </div>
                </div>
                <div>
                    <h3 class="fw-semibold">Hi, <span class="text-dark">{{ person.last_name|lower|capfirst|default:"John" }} {{ person.first_name|lower|capfirst|default:"Doe" }}</span>
                    </h3>
                    <span>Cheers, and happy activities - {{ date }}</span>
                </div>
            </div>
                </div>
                <div class="col-3">
                    <div class="text-center mb-n5">
                        <img src="{% static 'dashboard/dist/images/breadcrumb/ChatBc.png' %}" alt="" class="img-fluid mb-n4">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card card-body">
        <div class="table-responsive">
            <table class="table search-table align-middle text-nowrap">
                <thead class="header-item">
                <tr>
                    <th>
                        Days <br> --------------- <br> Time
                    </th>
                    <th>Mon</th>
                    <th>Tue</th>
                    <th>Wed</th>
                    <th>Thur</th>
                    <th>Fri</th>
                </tr>
                </thead>
                <tbody>
                <!-- start row -->
                <tr class="search-items">
                    <td>
                        <h6 class="user-name mb-0">8am - 9am</h6>
                    </td>
                    {% for course in first %}
                    <td>
                        <span>{{ course|linebreaks }}</span>
                    </td>
                    {% endfor %}
                </tr>
                <tr class="search-items">
                    <td>
                        <h6 class="user-name mb-0">9am - 10am</h6>
                    </td>
                    {% for course in second %}
                    <td>
                        <span>{{ course|linebreaks }}</span>
                    </td>
                    {% endfor %}
                </tr>
                <tr class="search-items">
                    <td>
                        <h6 class="user-name mb-0">10am - 11am</h6>
                    </td>
                    {% for course in third %}
                    <td>
                        <span>{{ course|linebreaks }}</span>
                    </td>
                    {% endfor %}
                </tr>
                <tr class="search-items">
                    <td>
                        <h6 class="user-name mb-0">11am - 12pm</h6>
                    </td>
                    {% for course in fourth %}
                    <td>
                        <span>{{ course|linebreaks }}</span>
                    </td>
                    {% endfor %}
                </tr>
                <tr class="search-items">
                    <td>
                        <h6 class="user-name mb-0">12pm - 1pm</h6>
                    </td>
                    {% for course in fifth %}
                    <td>
                        <span>{{ course|linebreaks }}</span>
                    </td>
                    {% endfor %}
                </tr>
                <tr class="search-items">
                    <td>
                        <h6 class="user-name mb-0">1pm - 2pm</h6>
                    </td>
                    {% for course in sixth %}
                    <td>
                        <span>{{ course|linebreaks }}</span>
                    </td>
                    {% endfor %}
                </tr>
                <tr class="search-items">
                    <td>
                        <h6 class="user-name mb-0">2pm - 3pm</h6>
                    </td>
                    {% for course in seventh %}
                    <td>
                        <span>{{ course|linebreaks }}</span>
                    </td>
                    {% endfor %}
                </tr>
                <tr class="search-items">
                    <td>
                        <h6 class="user-name mb-0">3pm - 4pm</h6>
                    </td>
                    <{% for course in eight %}
                    <td>
                        <span>{{ course|linebreaks }}</span>
                    </td>
                    {% endfor %}
                </tr>
                <!-- end row -->
                </tbody>
            </table>
        </div>
         <div class="text-center">
            <a class="btn btn-dark btn-lg" href="{% url 'Dashboard:generate' %}">Refresh Timetable</a>
        </div>
    </div>
</div>

{% endblock content %}

Dashboard/templates/dashboard/login.html
{% extends 'auth.html' %}

{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="col-sm-8 col-md-6 col-xl-9">
    <h2 class="mb-3 fs-7 fw-bolder">Timetable Management System</h2>
    <div class="position-relative text-center my-4">
        <p class="mb-0 fs-4 px-3 d-inline-block bg-white text-dark z-index-5 position-relative">Sign in with</p>
        <span class="border-top w-100 position-absolute top-50 start-50 translate-middle"></span>
    </div>
    <div id="toast">
        {% for message in messages %}
        <div class="alert alert-info" role="alert"><strong>Message: </strong><i>{{ message }}</i></div>
        {% endfor %}
    </div>
    <form method="post" action="">
        {% csrf_token %}
        {% include 'dashboard/form.html' with form=form %}
        <div class="d-flex align-items-center justify-content-between mb-4">
            <a class="text-primary fw-medium" href="{% url 'Dashboard:forgot_password' %}">Forgot Password ?</a>
        </div>
        <button type="submit" class="btn btn-primary w-100 py-8 mb-4 rounded-2">Sign In</button>
        <div class="d-flex align-items-center justify-content-center">
            <p class="fs-4 mb-0 fw-medium">Are you new?</p>
            <a class="text-primary fw-medium ms-2" href="{% url 'Dashboard:register' %}">Create an account</a>
        </div>
    </form>
</div>
{% endblock content %}

{% block ajax %}
$("#toast").fadeIn(3000);
$("#toast").fadeOut(3000);
{% endblock ajax %}

Dashboard/templates/dashboard/register.html
{% extends 'auth.html' %}

{% load static %}

{% block title %}Register{% endblock title %}

{% block content %}
<div class="col-sm-8 col-md-6 col-xl-9">
    <h2 class="mb-3 fs-7 fw-bolder">Timetable Management System</h2>
    <div class="position-relative text-center my-4">
        <p class="mb-0 fs-4 px-3 d-inline-block bg-white text-dark z-index-5 position-relative">Sign up with</p>
        <span class="border-top w-100 position-absolute top-50 start-50 translate-middle"></span>
    </div>
    <div id="toast">
        {% for message in messages %}
        <div class="alert alert-info" role="alert"><strong>Message: </strong><i>{{ message }}</i></div>
        {% endfor %}
    </div>
    <form method="post" action="">
        {% csrf_token %}
        {% include 'dashboard/form.html' with form=form %}
        <button type="submit" class="btn btn-primary w-100 py-8 mb-4 rounded-2">Register</button>
        <div class="d-flex align-items-center justify-content-center">
            <p class="fs-4 mb-0 fw-medium">Already own an account?</p>
            <a class="text-primary fw-medium ms-2" href="{% url 'Dashboard:login' %}">Login to account</a>
        </div>
    </form>
</div>
{% endblock content %}

{% block ajax %}
$("#toast").fadeIn(3000);
$("#toast").fadeOut(3000);
{% endblock ajax %}